default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST') %>
  port: <%= ENV.fetch('DB_PORT') %>
  pool: <%= ENV.fetch('DB_POOL') %>
  username: <%= ENV.fetch('DB_USER', nil) %>
  password: <%= ENV.fetch('DB_PASSWORD', nil) %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE') + "_test" %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE') + "_development" %>

production:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE') %>
